/*
* generated by Xtext
*/
package es.upm.gsi.ECharts.ui.contentassist;

import es.upm.gsi.ECharts.ui.contentassist.AbstractDslEChartsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DslEChartsProposalProvider extends AbstractDslEChartsProposalProvider {

}
