/*
* generated by Xtext
*/
package es.upm.gsi.ECharts.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslEChartsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("es/upm/gsi/ECharts/parser/antlr/internal/InternalDslECharts.tokens");
	}
}
