/*
 * generated by Xtext
 */
package es.upm.gsi.ECharts;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslEChartsRuntimeModule extends es.upm.gsi.ECharts.AbstractDslEChartsRuntimeModule {

}
