/*
 * generated by Xtext
 */
package es.upm.gsi.ECharts.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DslEChartsUiModule extends es.upm.gsi.ECharts.ui.AbstractDslEChartsUiModule {
	public DslEChartsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
