
/*
 * generated by Xtext
 */
package es.upm.gsi.ECharts.ui.internal;

import org.apache.log4j.Logger;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.BundleContext;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.util.Modules;

import java.util.Map;
import java.util.HashMap;

/**
 * Generated
 */
public class DslEChartsActivator extends AbstractUIPlugin {

	private Map<String,Injector> injectors = new HashMap<String,Injector>();
	private static DslEChartsActivator INSTANCE;

	public Injector getInjector(String languageName) {
		return injectors.get(languageName);
	}
	
	@Override
	public void start(BundleContext context) throws Exception {
		super.start(context);
		INSTANCE = this;
		try {
			
			injectors.put("es.upm.gsi.ECharts.DslECharts", Guice.createInjector(
				Modules.override(Modules.override(getRuntimeModule("es.upm.gsi.ECharts.DslECharts")).with(getUiModule("es.upm.gsi.ECharts.DslECharts"))).with(getSharedStateModule())
			));
			
		} catch (Exception e) {
			Logger.getLogger(getClass()).error(e.getMessage(), e);
			throw e;
		}
	}
	
	public static DslEChartsActivator getInstance() {
		return INSTANCE;
	}
	
	protected Module getRuntimeModule(String grammar) {
		
		if ("es.upm.gsi.ECharts.DslECharts".equals(grammar)) {
		  return new es.upm.gsi.ECharts.DslEChartsRuntimeModule();
		}
		
		throw new IllegalArgumentException(grammar);
	}
	protected Module getUiModule(String grammar) {
		
		if ("es.upm.gsi.ECharts.DslECharts".equals(grammar)) {
		  return new es.upm.gsi.ECharts.ui.DslEChartsUiModule(this);
		}
		
		throw new IllegalArgumentException(grammar);
	}
	
	protected Module getSharedStateModule() {
		return new org.eclipse.xtext.ui.shared.SharedStateModule();
	}
	
}
