/*
* generated by Xtext
*/
package es.upm.gsi.ECharts.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class DslEChartsTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
